# Generated by Django 5.2.8 on 2025-12-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_emailotp_code_alter_profile_phone_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='notes',
            name='note_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('qna', 'Q&A'), ('quiz', 'Quiz')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
