# Generated by Django 5.2.8 on 2025-12-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_emailotp_email_alter_emailotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='note_type',
            field=models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('qna', 'Q&A'), ('quiz', 'Quiz'), ('other', 'Other')], default='text', max_length=20),
        ),
    ]
